
#kp_tab: CHAIN_OPTIONS
64: PRESET
9: SCREEN_AUDIO_MIXER
22: ZYNSWITCH 1
104: ZYNSWITCH 3

106: SCREEN_ZYNPAD
63: SCREEN_PATTERN_EDITOR
86: TOGGLE_MIDI_PLAY
82: TOGGLE_MIDI_RECORD

79: SCREEN_SNAPSHOT
81: SCREEN_MIDI_RECORDER
89: ENTER_MIDI_LEARN
84 16: ZYNSWITH 0
87: ZYNSWITCH 1

80: ARROW_UP
88: ARROW_DOWN
83: ARROW_LEFT
85: ARROW_RIGHT

90: SCREEN_AUDIO_MIXER
90 16: SCREEN_ALSA_MIXER
91: MENU
91 16: SCREEN_ADMIN


