65 0: ALL_NOTES_OFF
65 1: ALL_SOUNDS_OFF

110 1: RESTART_UI
110 4: REBOOT
115 4: POWER_OFF
118 4: RELOAD_MIDI_CONFIG

31: ZYNSWITCH 0
45: ZYNSWITCH 1
22: ZYNSWITCH 1
9: ZYNSWITCH 1
32: ZYNSWITCH 2
46: ZYNSWITCH 3
36: ZYNSWITCH 3

60 4: ZYNPOT 1,1
59 4: ZYNPOT 1,-1
60 0: ZYNPOT 3,1
59 0: ZYNPOT 3,-1
60 5: ZYNPOT 0,1
59 5: ZYNPOT 0,-1
60 1: ZYNPOT 2,1
59 1: ZYNPOT 2,-1

38 0: START_AUDIO_RECORD
38 1: STOP_AUDIO_RECORD
38 8: TOGGLE_AUDIO_RECORD
38 4: START_AUDIO_PLAY
38 5: STOP_AUDIO_PLAY
38 12: TOGGLE_AUDIO_PLAY

58 0: START_MIDI_RECORD
58 1: STOP_MIDI_RECORD
58 8: TOGGLE_MIDI_RECORD
58 4: START_MIDI_PLAY
58 5: STOP_MIDI_PLAY
58 12: TOGGLE_MIDI_PLAY

116 0: ARROW_DOWN
111 0: ARROW_UP
114 0: ARROW_RIGHT
113 0: ARROW_LEFT

10: PROGRAM_CHANGE 1
11: PROGRAM_CHANGE 2
12: PROGRAM_CHANGE 3
13: PROGRAM_CHANGE 4
14: PROGRAM_CHANGE 5
15: PROGRAM_CHANGE 6
16: PROGRAM_CHANGE 7
17: PROGRAM_CHANGE 8
18: PROGRAM_CHANGE 9
19: PROGRAM_CHANGE 0
